services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/sensor_db  # Connection string to MongoDB

  db:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: sensor_db
    volumes:
      - db_data:/data/db
    restart: always

volumes:
  db_data:
